### ISSUE TITLE
本地npm install后运行报错

### ISSUE THREAD

**Issue by meteorain** [yuhangch/yuhang.ch#1]
astro  v4.16.10 ready in 6193 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

19:47:01 [ERROR] [MiddlewareCantBeLoaded] An unknown error was thrown while loading your middleware.
  Error reference:
    https://docs.astro.build/en/reference/errors/middleware-cant-be-loaded/
  Stack trace:
    at C:\Users\Vivian\Documents\Astro\yuhang.ch\node_modules\astro\dist\core\middleware\loadMiddleware.js:8:24
    [...] See full stack trace in the browser, or rerun with --verbose.
  Caused by:
  The following environment variables defined in `experimental.env.schema` are invalid:

- API_URL is missing

    at Module.createInvalidVariablesError (C:\Users\Vivian\Documents\Astro\yuhang.ch\node_modules\astro\dist\env\runtime.js:18:10)
    at eval (C:\Users\Vivian\Documents\Astro\yuhang.ch\astro:env\server:37:22)
19:47:01 watching for file changes...
19:47:09 [ERROR] [MiddlewareCantBeLoaded] An unknown error was thrown while loading your middleware.
  Error reference:
    https://docs.astro.build/en/reference/errors/middleware-cant-be-loaded/
  Stack trace:
    at loadMiddleware (file:///C:/Users/Vivian/Documents/Astro/yuhang.ch/node_modules/astro/dist/core/middleware/loadMiddleware.js:8:24)
    [...] See full stack trace in the browser, or rerun with --verbose.
  Caused by:
  The following environment variables defined in `experimental.env.schema` are invalid:

- API_URL is missing

    at Module.createInvalidVariablesError (C:\Users\Vivian\Documents\Astro\yuhang.ch\node_modules\astro\dist\env\runtime.js:18:10)
    at eval (C:\Users\Vivian\Documents\Astro\yuhang.ch\astro:env\server:37:22)

**Comment by yuhangch** [comment]
看起来是 缺少.env

STUDIO_SECRET=XXXXXXX
API_SECRET=XXXXXXX
API_URL=https://local.host/

这样的话应该能跑起来，但个别页面有问题
